version: '3.8'

services:
  tensorflow_serving:
    image: tensorflow/serving:latest
    ports:
      - "8501:8501"
    volumes:
      - ./project-1-model_4_p3_s14_saved_model:/models/project1
    environment:
      - MODEL_NAME=project1

  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MODEL_URL=http://tensorflow_serving:8501/v1/models/project1:predict
    depends_on:
      - tensorflow_serving
